name: Deploy

on:
  release:
    types: [created]
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Cache NPM Dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Dependencies
      run: npm install
      env:
        NODE_ENV: development
    - name: Build One App Page Wrapper
      run: npm run build
      env:
        NODE_ENV: production
    - name: 'Deploy'
      run: now build --prod --confirm -t $NOW_TOKEN
      env:
        NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
    - name: 'Update Module Map'
      run: |
        node ./scripts/updateModuleMap.js
        cd ./tmp
        now tmp --prod --confirm -t $NOW_TOKEN --name my-apartment-module-map
      env:
        NOW_TOKEN: ${{ secrets.NOW_TOKEN }}

